### ISSUE TITLE
-size should be -bitsize in Github Usage section.

### ISSUE THREAD

**Issue by NeoTeo** [whyrusleeping/ipfs-key#1]
Your Usage doc says to use 

`ipfs-key -size=4096 > my.key`
but the command is currently
`ipfs-key -bitsize=4096 > my.key`

:)

**Comment by wigy-opensource-developer** [comment]
As far as I can tell, this is already fixed on the master.

**Comment by whyrusleeping** [comment]
Yeap, this has been fixed
